### ISSUE TITLE
Contentful Js SDK

### ISSUE THREAD

**Issue by Khaledgarbaya** [danhayden/contentful-response-parser#1]
Hi @danhayden,

My name is Khaled and I am the maintainer of Contentful's javascript SDKs.
I just came across your project and I wanted to inform you that we already had these features in the [CDA SDK](https://github.com/contentful/contentful.js) and more like rate limiting etc.

Is there a reason that you are not using it? did you find any problem with our current SDK ?, the reason for my question is I am always trying to get feedback to help make the SDK easy to use.

Best,
Khaled

**Comment by danhayden** [comment]
Hi @Khaledgarbaya 

My main motivation was to have a minimal yet versatile library that I could use on several projects with very configurations and pre-existing dependencies. 

I decided not to include a HTTP client as many projects already have one included or developers have a preferred one that they like to use. I also wanted to avoid having dependencies to keep the file size down to decrease download time and parse time.

Also many of the features of Contentful's javascript SDKs I currently do not need. This results in this library weighing only 903B and fulfilling the use case I have compared to Contentful's javascript SDKs 27.6KB. 

Thanks,
Dan

**Comment by danhayden** [comment]
For reference I used the following files for the size comparison:

https://unpkg.com/contentful-response-parser@1.1.0
https://unpkg.com/contentful@3.0.0/browser-dist/contentful.min.js

**Comment by valentinvieriu** [comment]
@danhayden this is a great initiative!
@Khaledgarbaya maybe you guys can pick this up and make an official lightweight solution. Your SDK has a heavy impact on the size of the project, and might say that your data structure it's not the most friendly one when comes of working with nested data structures.
