### ISSUE TITLE
Deep nested Entries

### ISSUE THREAD

**Issue by valentinvieriu** [danhayden/contentful-response-parser#3]
Thank you for taking the time to write this script.The official Contentful SDK is so big, that there is a real need for something like your library.

I've tried to use it for my project, but I have a hard time getting deep nested Entities.
I have a more deeper structure with content models containing links to other contend models.
Here is a sample of my data structure:
[Here is my fiddle](https://jsfiddle.net/valentinvieriu/p9au79mp/)

As you can see it does not pick the heroItems.
I believe this type of nesting is a usual use case, would be great to see your library supporting it.

I've tried to fix it myself, but got lost on the nested recursive calls of `generateItemObject`

**Comment by danhayden** [comment]
Hey, thanks for your interest in the library and for opening an issue! 😀

The official Contentful SDK, although extremely useful, is indeed a very large dependency 😢 

This library was originally created for a very specific use case for a project which did not have deeply nested entires and therefore I did not and support for it to keep the bundle size down (currently less than 600 bytes gzipped).

However I do believe this would be a very useful feature and I have added an note to the readme about this limitation.

Unfortunately I do not currently have any capacity to investigate adding this feature but PRs are welcome if you and anyone else manages to make some progress on this 👍

**Comment by valentinvieriu** [comment]
I've found that contentfull have a lightweight solution for parsing the JSON
[contentful-response-parser](https://github.com/danhayden/contentful-response-parser)

This solved my nesting problem.
Thank you

**Comment by danhayden** [comment]
Thats good to hear 😃 
Would you mind sharing the solution you have found (link in your comment is this repo) as I'd be interested to take a look.
Thanks!

**Comment by sylvainlegault** [comment]
I would like so much that you support nesting...I found https://github.com/contentful/contentful-resolve-response but it is still output an ugly mess.
